
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ydiumywbxgenfblwwcqe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlkaXVteXdieGdlbmZibHd3Y3FlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwMzI2MzYsImV4cCI6MjA1ODYwODYzNn0.LMnESHqbCJoY1H6SvkjCNR7KeSF38y4sl9QQolyAlcM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
